image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd my-app
    - npm update -g npm
    - npm ci


unit-test-job:   # This job runs in the test stage.
  stage: test    
  script:
    -  cd my-app
    -  npm install firebase
    -  npm i react-scripts
    -  npm test

deploy:
  stage : deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/drp-askdoc-server.git
  - git push -f heroku master
  - echo "Deployed"


