
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:

unit-test-job:   # This job runs in the test stage.
  stage: test    
  script:
   
deploy-job:      # This job runs in the deploy stage.
  stage: deploy  
  script:

