image: node:latest

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm update -g npm
    - npm ci

unit-test-job: # This job runs in the test stage.
  stage: test
  script:
    - npm install firebase
    - npm i react-scripts
    - npm test

deploy:
  stage : deploy
  script:
  - git add .
  - git commit -am "Deploy to heroku"
  - git push heroku master
  - echo "Deployed"