stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first.
  image: node:latest
  stage: build
  script:
    - cd backend
    - npm ci


unit-test-job: # This job runs in the test stage.
  image: node:latest
  stage: test
  script:
    - npm i react-scripts
    - cd frontend
    - npm ci
    - npm test

deploy:
  image: ruby:latest
  stage : deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=drp-askdoc --api_key=$HEROKU_API_KEY
